---
- name: Build node
  hosts: build
  become: yes

  # variables
  artifact: hello-1.0.war

  tasks:
    - name: Ensure artifact directory exists
      file:
        path: /war
        state: directory
    
    - name: Ensure previously built artifact is absent
      file:
        path: "{{ artifact }}"
        state: absent

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker python extension is installed
      apt:
        name: python-docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Create build container
      docker_container:
        name: build
        state: started
        image: maven:3.6-alpine
        volumes:
          - /war:/war
        command: >
          /bin/bash -c "apk update
          && apk add git
          && git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git git
          && mvn -f /git/pom.xml package
          && cp /git/target/{{ artifact }} /war/"
        recreate: yes
        detach: no
        cleanup: yes