---
- name: Build node
  hosts: build
  become: yes

  vars:
    git_repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    artifact: hello-1.0.war

  tasks:
    - name: Ensure artifact directory exists
      file:
        path: /war
        state: directory
    
    - name: Ensure previously built artifact is absent
      file:
        path: "/war/{{ artifact }}"
        state: absent

    - name: Ensure Docker is installed
      apt:
        name:
          - docker.io
          - python-docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Create build container
      docker_container:
        name: build
        state: started
        image: maven:3.6-alpine
        volumes:
          - /war:/war
        command: >
          /bin/bash -c "apk update
          && apk add git
          && git clone {{ git_repo }} git
          && mvn -f /git/pom.xml package
          && cp /git/target/{{ artifact }} /war/"
        recreate: yes
        detach: no
        cleanup: yes
    
    - name: Ensure newly built artifact is present
      file:
        path: "/war/{{ artifact }}"
        state: present
    
    - name: Copy Dockerfile to Buildnode
      copy:
        src: Dockerfile
        dest: /dockerfile/Dockerfile

    - name: Build production image
      docker_image:
        name: atercat/myboxfuse:tomcat
        dockerfile: /dockerfile/Dockerfile
        buildargs: "artifact:/war/{{ artifact }}"
        state: build
        push: yes